### ISSUE TITLE
Add support for multiple containers in a task definition

### ISSUE THREAD

**Issue by aleksy-zalenski** [cn-terraform/terraform-aws-ecs-fargate-task-definition#13]
Hello,

Currently I do not see an option of definining multiple containers in a single task definition. This option would come in handy in some cases where we need two different docker containers to run in the same task (e.g. PHP+Nginx). 

Would it be at all possible to support such scenario? Something similar to this: https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/examples/multiple_definitions/main.tf 

Thanks!

**Comment by jnonino** [comment]
Released in version 1.0.27
