### ISSUE TITLE
Issue in version `1.0.23` - An argument named "tags" is not expected here

### ISSUE THREAD

**Issue by igadelshina-pbp** [cn-terraform/terraform-aws-ecs-fargate-task-definition#15]
Hi, thank you for creating terraform modules.

When I reference version 1.0.23 I get the following error in plan:
```
Error: Unsupported argument
  on .terraform/modules/.../main.tf line 21, in resource "aws_iam_policy" "ecs_task_execution_role_custom_policy":
  21:   tags        = var.tags
An argument named "tags" is not expected here.
```

I get it both when I specify `tags` , e.g.:
```
module "test" {
  source          = "cn-terraform/ecs-fargate-task-definition/aws"
  version         = "1.0.23"
  name            = test
  tags            = local.default_tags
}
```
and when I don't specify it (even though this var is supposed to be optional?)

Please take a look when you have a moment. Thanks!

**Comment by jnonino** [comment]
Hi, I'm closing this issue as it has been a long time without new reports. If you find this is still happening, please reopen.
