### ISSUE TITLE
input task_execution_role

### ISSUE THREAD

**Issue by ChihSeanHsu** [cn-terraform/terraform-aws-ecs-fargate-task-definition#3]
Can you enhance this feature?
There are lot of usages like ECS need to access data from dynamodb or container secrets need access from SSM etc..

**Comment by idriver91** [comment]
@Vincentsean @jnonino Looks like this has already been started. We were looking for the same change to be made.

https://github.com/tuvshuud/terraform-aws-ecs-fargate-task-definition/commit/2c99899fb6a89d08b426e1167bea82e6170163ab

**Comment by tuvshuud** [comment]
Sure. I will open a PR tomorrow

**Comment by jnonino** [comment]
Thanks for you work @tuvshuud @idriver91 !!!

The PR is already merged and the change is available in the new version [1.0.12](https://registry.terraform.io/modules/cn-terraform/ecs-fargate-task-definition/aws/1.0.12).
